export const ICONS = {
  light: {
    logo: 'assets/images/light/logo.svg',
    actions: {
      back: 'assets/svg/back_icon.svg',
    },
    splash: {
      logo: 'assets/images/light/splash-logo.svg',
      step1: 'assets/images/step-1.png',
      step2: 'assets/images/step-2.png',
      step3: 'assets/images/step-3.png',
      vector1: 'assets/images/vector-1.png',
      vector2: 'assets/images/vector-2.png',
      vector3: 'assets/images/vector-3.png',
    },
    geo: 'assets/icon/light/geo.svg',
    messaging: 'assets/icon/light/messaging.svg',
    mic: 'assets/icon/light/mic.svg',
    profile: 'assets/icon/light/profile.svg',
    theme: 'assets/icon/light/theme.svg',
    star: 'assets/icon/light/star.svg',
    hash: 'assets/icon/light/hash.svg',
    send: 'assets/icon/light/send.svg',
    location: 'assets/icon/light/location.svg',
    support: 'assets/icon/light/support.svg',
    close: 'assets/icon/light/close.svg',
    yellowReviewStar: 'assets/icon/yellow-review-star.svg',
    dragIcon: 'assets/icon/drag_icon.svg',
    addMapsLocation: 'assets/icon/maps-add-icon.svg',
    footer: {
      home: 'assets/icon/footer/light/home.svg',
      clients: 'assets/icon/footer/light/clients.svg',
      add: 'assets/icon/footer/add.svg',
      statistics: 'assets/icon/footer/light/statistics.svg',
      account: 'assets/icon/footer/light/account.svg',
      selected: {
        home: 'assets/icon/footer/selected-home.svg',
        clients: 'assets/icon/footer/selected-clients.svg',
        statistics: 'assets/icon/footer/selected-statistics.svg',
        account: 'assets/icon/footer/selected-account.svg',
      },
      guruFooter: {
        home: 'assets/icon/footer/guru-footer/light/home.svg',
        homeActive: 'assets/icon/footer/guru-footer/active/home.svg',
        heart: 'assets/icon/footer/guru-footer/light/heart.svg',
        heartActive: 'assets/icon/footer/guru-footer/active/heart.svg',
        chat: 'assets/icon/footer/guru-footer/light/chat.svg',
        chatActive: 'assets/icon/footer/guru-footer/active/chat.svg',
        itineraries: 'assets/icon/footer/guru-footer/light/Itineraries.svg',
        itinerariesActive: 'assets/icon/footer/guru-footer/active/Itineraries.svg',
        profile: 'assets/icon/footer/guru-footer/light/profile.svg',
        profileActive: 'assets/icon/footer/guru-footer/active/profile.svg',
      },
    },
    header: {
      back: 'assets/icon/header/light/back.svg',
      back2: 'assets/svg/back2.svg',
      notification: 'assets/icon/header/light/notification.svg',
      menu: 'assets/icon/header/menu.svg',
      notificationAlert: 'assets/icon/header/notification-alert.svg',
      dateIcon: 'assets/icon/date.svg',
      coin: 'assets/icon/coin.svg',
    },
    messageTakeoverFab: {
      context: 'assets/icon/message-takeover-fab/dark/context.svg',
      live: 'assets/icon/message-takeover-fab/dark/live.svg',
      scan: 'assets/icon/message-takeover-fab/dark/scan.svg',
      translate: 'assets/icon/message-takeover-fab/dark/translate.svg',
      vent: 'assets/icon/message-takeover-fab/dark/vent.svg',
      close: 'assets/icon/message-takeover-fab/dark/fab-close.svg',
    },
    unmatched: {
      hash: 'assets/icon/light/hash.svg',
      star: 'assets/icon/light/star.svg',
      edit: 'assets/icon/light/edit.svg',
    },
    paymentCard: {
      mastercard: 'assets/icon/light/card-brands/mastercard.svg',
      visa: 'assets/icon/light/card-brands/visa.svg',
      americanExpress: 'assets/icon/light/card-brands/american-express.svg',
    },
    password: {
      lock: 'assets/icon/light/password/lock.svg',
      unlock: 'assets/icon/light/password/unlock.svg',
      mail: 'assets/icon/light/password/mail.svg',
    },
    accountSetup: {
      googleCalender: 'assets/icon/social/google-calendar.svg',
      microsoft: 'assets/icon/social/microsoft.svg',
    },
    common: {
      arrowRight: 'assets/icon/light/common/arrow-right.svg',
      dates: 'assets/icon/light/common/dates.svg',
      earnings: 'assets/icon/light/common/earnings.svg',
      notification: 'assets/icon/light/common/notification.svg',
      arrowDown: 'assets/icon/arrow_down.svg',
    },
    separator: 'assets/icon/light/separator.svg',
    calendar: 'assets/icon/light/calendar.svg',
    locationSolid: 'assets/icon/light/location-solid.svg',
    time: 'assets/icon/light/time.svg',
    profession: 'assets/icon/unmatched-registration/profession.svg',
    love: 'assets/icon/unmatched-registration/love.svg',
    info: 'assets/icon/unmatched-registration/info.svg',
    guru: {
      accountType: 'assets/icon/light/guru/account_type.svg',
      dates: 'assets/icon/light/guru/dates.svg',
      money: 'assets/icon/light/guru/money.svg',
      rentNumber: 'assets/icon/light/guru/rente_number.svg',
      password: 'assets/icon/light/guru/password.svg',
    },
  },
  dark: {
    logo: 'assets/images/logo.svg',
    actions: {
      back: 'assets/svg/back_icon_dark.svg',
    },
    splash: {
      logo: 'assets/images/splash-logo.svg',
      step1: 'assets/images/step-1.png',
      step2: 'assets/images/step-2.png',
      step3: 'assets/images/step-3.png',
      vector1: 'assets/images/vector-1.png',
      vector2: 'assets/images/vector-2.png',
      vector3: 'assets/images/vector-3.png',
    },
    geo: 'assets/icon/dark/geo.svg',
    messaging: 'assets/icon/dark/messaging.svg',
    mic: 'assets/icon/dark/mic.svg',
    profile: 'assets/icon/profile.svg',
    theme: 'assets/icon/theme.svg',
    star: 'assets/icon/star.svg',
    hash: 'assets/icon/hash.svg',
    send: 'assets/icon/send.svg',
    location: 'assets/icon/location.svg',
    support: 'assets/icon/support.svg',
    close: 'assets/icon/dark/close.svg',
    yellowReviewStar: 'assets/icon/yellow-review-star.svg',
    dragIcon: 'assets/icon/drag_icon.svg',
    addMapsLocation: 'assets/icon/maps-add-icon.svg',
    footer: {
      home: 'assets/icon/footer/dark/home.svg',
      clients: 'assets/icon/footer/dark/clients.svg',
      add: 'assets/icon/footer/add.svg',
      statistics: 'assets/icon/footer/dark/statistics.svg',
      account: 'assets/icon/footer/dark/account.svg',
      selected: {
        home: 'assets/icon/footer/selected-home.svg',
        clients: 'assets/icon/footer/selected-clients.svg',
        statistics: 'assets/icon/footer/selected-statistics.svg',
        account: 'assets/icon/footer/selected-account.svg',
      },
      guruFooter: {
        home: 'assets/icon/footer/guru-footer/light/home.svg',
        homeActive: 'assets/icon/footer/guru-footer/active/home.svg',
        heart: 'assets/icon/footer/guru-footer/light/heart.svg',
        heartActive: 'assets/icon/footer/guru-footer/active/heart.svg',
        chat: 'assets/icon/footer/guru-footer/light/chat.svg',
        chatActive: 'assets/icon/footer/guru-footer/active/chat.svg',
        itineraries: 'assets/icon/footer/guru-footer/light/Itineraries.svg',
        itinerariesActive: 'assets/icon/footer/guru-footer/active/Itineraries.svg',
        profile: 'assets/icon/footer/guru-footer/light/profile.svg',
        profileActive: 'assets/icon/footer/guru-footer/active/profile.svg',
      },
    },
    header: {
      back: 'assets/icon/header/dark/back.svg',
      back2: 'assets/svg/back2.svg',
      notification: 'assets/icon/header/dark/notification.svg',
      menu: 'assets/icon/header/menu.svg',
      notificationAlert: 'assets/icon/header/notification-alert.svg',
      dateIcon: 'assets/icon/date.svg',
      coin: 'assets/icon/coin.svg',
    },
    messageTakeoverFab: {
      context: 'assets/icon/message-takeover-fab/light/context.svg',
      live: 'assets/icon/message-takeover-fab/light/live.svg',
      scan: 'assets/icon/message-takeover-fab/light/scan.svg',
      translate: 'assets/icon/message-takeover-fab/light/translate.svg',
      vent: 'assets/icon/message-takeover-fab/light/vent.svg',
      close: 'assets/icon/message-takeover-fab/light/fab-close.svg',
    },
    paymentCard: {
      mastercard: 'assets/icon/dark/card-brands/mastercard.svg',
      visa: 'assets/icon/dark/card-brands/visa.svg',
      americanExpress: 'assets/icon/dark/card-brands/american-express.svg',
    },
    password: {
      lock: 'assets/icon/dark/password/lock.svg',
      unlock: 'assets/icon/dark/password/unlock.svg',
      mail: 'assets/icon/dark/password/mail.svg',
    },
    accountSetup: {
      googleCalender: 'assets/icon/social/google-calendar.svg',
      microsoft: 'assets/icon/social/microsoft.svg',
    },
    common: {
      arrowRight: 'assets/icon/dark/common/arrow-right.svg',
      dates: 'assets/icon/dark/common/dates.svg',
      earnings: 'assets/icon/dark/common/earnings.svg',
      notification: 'assets/icon/dark/common/notification.svg',
      arrowDown: 'assets/icon/arrow_down.svg',
    },
    separator: 'assets/icon/dark/separator.svg',
    calendar: 'assets/icon/dark/calendar.svg',
    locationSolid: 'assets/icon/dark/location-solid.svg',
    time: 'assets/icon/dark/time.svg',
    profession: 'assets/icon/unmatched-registration/profession.svg',
    love: 'assets/icon/unmatched-registration/love.svg',
    info: 'assets/icon/unmatched-registration/info.svg',
    guru: {
      accountType: 'assets/icon/dark/guru/account_type.svg',
      dates: 'assets/icon/dark/guru/dates.svg',
      money: 'assets/icon/dark/guru/money.svg',
      rentNumber: 'assets/icon/dark/guru/rente_number.svg',
      password: 'assets/icon/dark/guru/password.svg',
    },
  },
  commonIcons: {
    plus: 'assets/icon/common/plus.svg',
    sliders: 'assets/icon/common/sliders.svg',
    calendarFilter: 'assets/icon/calendar/calendar-filter.svg',
    speaker: 'assets/icon/common/speaker.svg',
  },
};
